spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  codec:
    max-in-memory-size: 100MB

  datasource:
    url: jdbc:mysql://localhost/lookit
    username: "root"
    password: "Lookit@0302"

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    redis:
      host: localhost
      port: 6379

  kakao:
    client_id: ${KAKAO_CLIENT_ID}
    base_url: https://dapi.kakao.com
    redirect_uri: https://lookit-pearl.vercel.app/auth/kakao/callback

fitting:
  queue:
    consumer-timeout-seconds: 60

logging:
  level:
    io.netty: DEBUG

jwt:
  secret-key: ${JWT_SECRET}
  access-token-expire-period: 1800000
  refresh-token-expire-period: 3600

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY}
      secret-key: ${AWS_SECRET_KEY}
    region:
      static: ap-northeast-2
    s3:
      bucket: lookit-bucket
